---
- name: Ensure apt cache is updated (Debian/Ubuntu)
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Install Fish shell (Debian/Ubuntu)
  ansible.builtin.apt:
    name: fish
    state: present
  when: ansible_os_family == "Debian"

- name: Check if k3s-uninstall.sh exists and run it
  ansible.builtin.command: /usr/local/bin/k3s-uninstall.sh
  args:
    removes: /usr/local/bin/k3s-uninstall.sh
  ignore_errors: yes
  changed_when: true

- name: Append fs.inotify settings to sysctl.conf
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: "{{ item }}"
    state: present
  loop:
    - fs.inotify.max_user_instances=100000
    - fs.inotify.max_user_watches=100000

- name: Apply sysctl changes
  ansible.builtin.command: sysctl -p
  changed_when: true

- name: Create K3s configuration directory
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    mode: '0755'

- name: Copy reg-ca.crt to K3s configuration
  ansible.builtin.copy:
    content: |
      -----BEGIN CERTIFICATE-----
      MIIFdTCCA12gAwIBAgIUaijJzh7/YXch+cp8Fm6DYboBYoUwDQYJKoZIhvcNAQEN
      BQAwSjELMAkGA1UEBhMCVVMxETAPBgNVBAoMCGFwcHNjb2RlMREwDwYDVQQLDAhQ
      ZXJzb25hbDEVMBMGA1UEAwwMYXBwc2NvZGUuY29tMB4XDTI1MDExMTA0MzMyOFoX
      DTM1MDEwOTA0MzMyOFowSjELMAkGA1UEBhMCVVMxETAPBgNVBAoMCGFwcHNjb2Rl
      MREwDwYDVQQLDAhQZXJzb25hbDEVMBMGA1UEAwwMYXBwc2NvZGUuY29tMIICIjAN
      BgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAxZsZsi4FfK5hutO99APlmws3vvdG
      yI9QpMUvKCMPyWivJeg9lkgsddOAEjDsIdM76hAof8g7z488hHRH2/qeha2t3esf
      vZLoU2ewawcR24zis0pPc78mDoQX8SE/MxPsjSIbTuqzFWtE70Mry3+xTlXSKjX5
      szU13BJ9vXN2qifKcwkFq2A3qLENZqOjeYOznRbqpkLMfU2zmqWenaxr8JHwiuJl
      Rfdl8X2IhGyy/yG3yHtmTePWcMwnaU9WgvROtC5vglWvumf2XPi+PQn7zF4D4ybg
      R6dsNLm12RTGV9daOGzQ5h8W8iNd4tydYzoELVQmPGNoYm4QqT3pwLweduUD4jOe
      /tL5C/znAUYG/Md4LFm+6Bm8ktqORdc1sX0RdziKs5Xbnb/VKPUfMVAr6K6ShKJD
      5BLWoRJe9e4FRviJk5Tis29/qxj81jOEd+romhf5Di9DWfmAMx5SicJmV2Ag4mAu
      GK7Rrvlqza09zc/ITMz1NCL0GWQ9u/bPoYJWw+xFxVrAjgrow8KhsyKEIgL311MQ
      MPOHZVbfd00eOpnd0SPzaPaJdKbYxABoGZlF2tdpGQRSNUpOjYQ6xC5dRadoVY2g
      NhGAV+BDYcpmCVK4i3QR1093ACl8868KAHnRfeZOYOfo2LJcHPCjCMzVVRsXHxHv
      VwiMsPDHQVxUJvkCAwEAAaNTMFEwHQYDVR0OBBYEFKFvJ8xHpfrvymY5wwmLn/2l
      m1MyMB8GA1UdIwQYMBaAFKFvJ8xHpfrvymY5wwmLn/2lm1MyMA8GA1UdEwEB/wQF
      MAMBAf8wDQYJKoZIhvcNAQENBQADggIBAA68oplyuHziv86lADoqVGaXwHxjhZ5S
      ALSJks1D/19yvY0t52Fq0KIxuirZtfCdu/BYW8RxmeLFcRbvtdLMMFP3tlAzzppj
      PlEgH4t6awUczKM9CBp08aXSNWeBErWPqB1J1UqkPiCC8Hs0E8LelmPSzDkoAjvC
      H+S7jHcTOZVrtAUzhdOFUrA5ryTmat+THcAxYaOC/91QCYcCAujhgrzABZAeKcjx
      4K+VgvpRbBsb4kvxb/S3jNIzFBZQoS6/OJAuOU4rkWyRFJwDCaXd45pu4nHqa6JV
      ZGXi2DuTgrvyb2itYpFruFJBvBUzrUYY+w9hnqn9cIvBrgnN7lVldff1gbKoKl7i
      gyRJXTaYIAUFWEgmnIBHsvj6tzAzlfP4Xp5be/pBRjnmU7wLU5vfM0tzspCUrlon
      BrCAaC4vxknck8tAZDiYFhejTfVPMNWBMFoloquPToYbZest5TO6CNiRJd2lWTRX
      gIC23XGEUl+N0lpRZpbd/ZmPxqoTJTtgXHKFLg6AogWfTvjCDdeZkZMFIJARS/cq
      lrhrdyYB/Yd1YzPQRU88GbqC/Bkof1aIoFJrD3/2q8HB352erzQvvVeUr1AibtVn
      fAEYssuxg4/fYX4KNbNTnqGd0Cezy/kIYwY5sn2FIiUIit+e4Lh33gXq6ReCX3Hb
      lcI02rEEYenJ
      -----END CERTIFICATE-----
    dest: /etc/rancher/k3s/reg-ca.crt
    mode: '0644'

- name: Configure K3s registries.yaml
  ansible.builtin.copy:
    content: |
      configs:
        0.1.acdc.appscode.ninja:
          tls:
            ca_file: /etc/rancher/k3s/reg-ca.crt
    dest: /etc/rancher/k3s/registries.yaml
    mode: '0644'

- name: Install K3s with custom configuration
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable=traefik --disable=metrics-server" sh -s - --tls-san "10.2.0.76"
  args:
    executable: /bin/bash
  changed_when: true
  register: k3s_install
  failed_when: k3s_install.rc != 0 and 'already exists' not in k3s_install.stderr

- name: Configure bash aliases and environment variables
  ansible.builtin.blockinfile:
    path: /home/{{ ansible_user }}/.bashrc
    block: |
      alias k=kubectl
      export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
    marker: "# {mark} ANSIBLE MANAGED BLOCK for K3s"
    create: yes
    mode: '0644'

- name: Source bashrc for current session
  ansible.builtin.shell: source /home/{{ ansible_user }}/.bashrc
  args:
    executable: /bin/bash
  changed_when: false

- name: Wait for coredns deployment to be created
  ansible.builtin.shell: |
    kubectl wait --for=create -n kube-system deploy/coredns --timeout=10s
  args:
    executable: /bin/bash
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  changed_when: false
  retries: 5
  delay: 5
  register: coredns_wait
  until: coredns_wait.rc == 0


- name: Fetch KUBECONFIG file to local directory with IP-based filename
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "./kubeconfig/k3s-{{ ansible_host }}.yaml"
    flat: yes
  changed_when: true

- name: Replace 127.0.0.1 with node IP in KUBECONFIG file
  ansible.builtin.replace:
    path: /etc/rancher/k3s/k3s.yaml
    regexp: 'https://127\.0\.0\.1:6443'
    replace: 'https://{{ ansible_host }}:6443'
    mode: '0644'
  changed_when: true

- name: Fetch KUBECONFIG file to local directory with IP-based filename
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "./kubeconfig/k3s-{{ ansible_host }}.yaml"
    flat: yes
  changed_when: true

- name: Get kube-system namespace UID
  ansible.builtin.shell: |
    kubectl get ns kube-system -o=jsonpath='{.metadata.uid}'
  args:
    executable: /bin/bash
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  register: kube_system_uid
  become: yes
  changed_when: false

- name: Save kube-system UID to local file
  ansible.builtin.copy:
    content: "{{ kube_system_uid.stdout }}"
    dest: "./kubeconfig/kube-system-uid-{{ ansible_host }}.txt"
    mode: '0644'
  delegate_to: localhost
  become: no
  changed_when: true

#- name: Modify KUBECONFIG locally to use node IP
#  ansible.builtin.command: |
#    sed 's|https://127\.0\.0\.1:6443|https://{{ ansible_host }}:6443|' ./kubeconfig/temp-{{ ansible_host }}.yaml > ./kubeconfig/k3s-{{ ansible_host }}.yaml
#  delegate_to: localhost
#  changed_when: true
#
#- name: Remove temporary KUBECONFIG file
#  ansible.builtin.file:
#    path: "./kubeconfig/temp-{{ ansible_host }}.yaml"
#    state: absent
#  delegate_to: localhost
#  changed_when: true