---
- name: Test Ansible Connection
  hosts: all
  become: yes
  remote_user: ubuntu
#  roles:
#    - handlers
  vars:
    # 1. String Variable
    main_playbook_variable: "Hello, world in main playbook!"
    # 2. Dictionary Variable
    is_enabled: true
    #3. List Variable
    fruits:
      - apple
      - banana
      - orange
    # 4. Dictionary variable
    fruit_prices:
      apple: 0.5
      banana: 0.25
      orange: 0.75
    # 5. Referencing nested variable
    fruit_basket:
      - name: John
        fruits:
          - apple
          - orange
      - name: Jane
        fruits:
          - banana
          - apple

#  handlers:
#    - name: Restart Nginx
#      service:
#        name: nginx
#        state: restarted
  vars_files:
    - my_vars.yml
  tasks:
    - name: String Variable from - main_playbook_variable
      debug:
        var: main_playbook_variable

    - name: Boolean variable
      debug:
        msg: "Variable is true"
      when: is_enabled

    - name: List variables - print list of fruits
      debug:
        var: fruits

    - name: List variables - Refrence indivisual item in list
      debug:
        var: fruits[0]

    - name: Distionary variables
      debug:
        var: fruit_prices

    - name: Distionary variables- perticular elements
      debug:
        var: fruit_prices.apple

    - name: Distionary variables- perticular elements with different approach
      debug:
        var: fruit_prices["apple"]

    - name: Get the price of an apple
      command: echo "{{ fruit_prices['apple'] }}"
      register: apple_price_as_registered_var

    - name: Print the value of registered variable
      debug:
        var: apple_price_as_registered_var.stdout

    - name: Get the value of apple from the nested variables
      debug:
        var: fruit_prices[fruit_basket[0].fruits[0]]

    - name: Get the value of variable from my-vars.yaml
      debug:
        var: vars_from_my_vars_yaml
    - name: Get the value of variable from runtime
      debug:
        var: version

    - name: Get the value of variable from runtime2
      debug:
        var: other_variable




















